<a href="https://colab.research.google.com/github/NarongkiatPW/DADS/blob/DADS6003_Machine_Learning/ML_Practice1_Regression_6610422004.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pickle
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt #dpi 600
import seaborn as sns

In [13]:
df = pd.read_csv('https://raw.githubusercontent.com/NarongkiatPW/DADS/DADS6003_Machine_Learning/Housing.csv')
df.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished

In [14]:
df.shape

(545, 13)

In [15]:
# df.head(10)
df2 =df.copy()
# df2['mainroad'] = df2['mainroad'].apply(lambda x: '1' if x == 'yes' else '0')
df2['mainroad'] = np.where(df2['mainroad'] == 'yes', '1', '0').astype(int)
df2['guestroom'] = np.where(df2['guestroom'] == 'yes','1','0').astype(int)
df2['basement'] = np.where(df2['basement']== 'yes', '1','0').astype(int)
df2['hotwaterheating'] = np.where(df2['hotwaterheating'] =='yes','1','0').astype(int)
df2['airconditioning'] = np.where(df2['airconditioning'] == 'yes','1','0').astype(int)
df2['prefarea'] = np.where(df2['prefarea'] =='yes','1','0').astype(int)
df2['furnishingstatus'] = np.where(df2['furnishingstatus'] =='furnished','1',np.where(df2['furnishingstatus'] =='semi-furnished','0.5','0')).astype(float)
df2.head(20)
# print(df.shape)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,1.0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,1.0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,0.5
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,1.0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,1.0
5,10850000,7500,3,3,1,1,0,1,0,1,2,1,0.5
6,10150000,8580,4,3,4,1,0,0,0,1,2,1,0.5
7,10150000,16200,5,3,2,1,0,0,0,0,0,0,0.0
8,9870000,8100,4,1,2,1,1,1,0,1,2,1,1.0
9,9800000,5750,3,2,4,1,1,0,0,1,1,1,0.0
10,9800000,13200,3,1,2,1,0,1,0,1,2,1,1.0
11,9681000,6000,4,3,2,1,1,1,1,0,2,0,0.5
12,9310000,6550,4,2,2,1,0,0,0,1,1,1,0.5
13,9240000,3500,4,2,2,1,0,0,1,0,2,0,1.0
14,9240000,7800,3,2,2,1,0,0,0,0,0,1,0.5
15,9100000,6000,4,1,2,1,0,1,0,0,2,0,0.5
16,9100000,6600,4,2,2,1,1,1,0,1,1,1,0.0
17,8960000,8500,3,2,4,1,0,0,0,1,2,0,1.0
18,8890000,4600,3,2,2,1,1,0,0,1,2,0,1.0
19,8855000,6420,3,2,2,1,0,0,0,1,1,1,0.5

In [16]:
# กำหนด x และ y
col_x = ['area','bedrooms','bathrooms','stories','mainroad','guestroom','basement','hotwaterheating','airconditioning','parking','prefarea','furnishingstatus']
x = np.array(df2[col_x])
y = np.array(df2['price'])

# Function approximation f:x->y, f:R(n rows*d column)-> R (n rows*1 column)
# x_b= np.c_[np.ones((x.shape[0],1)),x] # n rows*1 col โดยใช้ np.ones บอก row*col และ np.c_ -> concat 1:1  ของตัวหน้ากับตัวหลัง

# หา theta โดยการ call inverse function from linear algebra module
# theta = np.linalg.inv(x_b.T.dot(x_b)).dot(x_b.T).dot(y)
# theta

# Multiple Linear Regression

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [22]:
# Split data train 80%, test 20%
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# สร้าง Model
lin_reg = LinearRegression()
# Train Model
lin_reg.fit(x_train,y_train)
print(lin_reg.intercept_, " , ",lin_reg.coef_)

#Prediction
y_predict = lin_reg.predict(x_test)
print(f"x_test.shape = {x_test.shape}")
print(f"y_predict = {y_predict}")

-406907.4631756218  ,  [2.53732234e+02 1.26430216e+05 1.00306572e+06 4.31159234e+05
 4.34983941e+05 3.95198712e+05 3.30288607e+05 1.20896581e+06
 8.59967238e+05 2.20086777e+05 6.93749764e+05 5.11313672e+05]
x_test.shape = (109, 12)
y_predict = [ 4019080.69890147  6258021.76856399  4392719.13411048  7335082.21688194
  2892857.56615675  7084655.57701774  3258634.73504731  3196499.16068631
  3520106.01134941  8359610.28845464  6646926.36096856  3788844.63269237
  3734072.96467981  4616010.40973202  3946124.94405792  2023177.4684687
  3975554.48783028  3624716.9650089   3210282.74216168  4668411.38105794
  5893719.66376515  6415683.83807236  4657036.55831934  2704096.11205267
  5356909.86181449  5740682.56798042  5337586.47961082  5444859.96648235
  5702144.57144374  5865872.30432732  3307327.30668416  6299491.02684292
  7123479.95544321  2960326.86653052  4424323.19483819  5125081.85591295
  4947693.93115736  3629027.81981122  2975421.52734786  3975089.5402192
  8106313.95534003  5014658.87529549  6469749.69804857  3566139.31348661
  3868652.86219465  6344993.74699856  4482572.73153155  2740240.0896807
  4105384.15298296  6518557.36176521  3976558.93952635  7056307.68945588
  2586714.16696756  2947687.80114419  3553624.39318115  5151386.47910423
  7171548.10937836  4052242.7088535   2884254.74264866  4379165.55939617
  6066225.12442544  6751773.9153444   3382551.41414111  7251896.59353497
  2681431.47017136  5138914.7819742   6685740.04693819  2619223.85247951
  3824989.41251459  4995902.7824292   4352358.99961469  7264572.3528292
  5150347.40449781  5947769.21201797  4086573.09797569  4549426.52941342
  2958392.04612462  7660252.98149768  2656282.61262027  3679497.40060293
  4352358.99961469  5981887.99426369  5132525.06975503  5458725.16176889
  3822006.6426444   4128176.81504507  4698794.75914507  5027920.2150587
  3913610.13040526  4296868.64305712  3290316.24497529  5880621.00664527
  3150060.86792803  3668445.62490134  4539382.03106222 10575679.21780643
  2971774.44221851  7093653.99925703  4418061.7711239   4577913.07853262
  6542179.32091921  3322929.37680988  4620712.65928556  3364236.62346779
  7400967.88555256  5138942.23888226  4058811.42233283  4972825.57184573
  6367950.02587764]

In [24]:
# หา MSE
from sklearn.metrics import mean_squared_error, r2_score
mean_squared_error(y_test, y_predict)
print(f"MSE = {mean_squared_error(y_test, y_predict)}")

# print(f"y.shape = {y.shape}")
# print(f"y_predict.shape = {y_predict.shape}")
# print(f"y_train.shape = {y_train.shape}")
# print(f"y_test.shape = {y_test.shape}")

MSE = 986041803890.0265

In [25]:
"""Deploy"""
print("Deploy")
pickle.dump(lin_reg, open('ml_6610422004.sav','wb') )
from google.colab import files
files.download('ml_6610422004.sav')

Deploy